version: "3"
services:
  postgres_primary:
    build: ./postgres/primary
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polyominoes
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  postgres_data:
