version: "3"
services:

  application:
    build: spring-application
    restart: unless-stopped
    depends_on:
      postgres_primary:
        condition: service_started
    ports:
      - '0.0.0.0:8080:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:postgresql://postgres_primary:5432/polyominoes",
            "spring.datasource.username" : "postgres",
            "spring.datasource.password" : "admin",
            "spring.datasource.driverClassName" : "org.postgresql.Driver",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    networks:
      default:
        aliases:
          - app_cluster

  postgres_primary:
    build: ./postgres/primary
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polyominoes
      - POSTGRES_APP_USER=polyominoes
      - POSTGRES_APP_PASSWORD= appPassword
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  postgres_data:
